### PR TITLE
Set max DKP/Perc value when updating the current item

### LINKED ISSUE #276: Bid window using wrong item icon
v2.1.2 in Classic.
The bid windows often show the wrong item icon, but the correct item name. Example here: https://i.imgur.com/g7rc7Tz.png.
Mousing over the icon would show the stats for the incorrect item, which would be some other item dropped by the same boss.
Our loot master is starting bids with /dkp bid [itemlink].

### PR DESCRIPTION
**Pull request by quiqua**
With recent changes, the `MonDKP:CurrItem_Set` method takes 4 values:
- name,
- min dkp
- max dkp
- and icon

This PR will pass the 3 argument as max-dkp and not as icon and should hopefully fix https://github.com/Roeshambo/MonolithDKP/issues/276

### CODE REVIEW

**Comment by lantisnt** [comment]
@quiqua  Thanks for noticing, I've missed that when adding max bid value but I think this wont work as maxBid is not accessible in percentage mode.  Set the 3rd parameter as 0  (see line 598, 2 above yours change)

File: Modules/Bidding.lua [hunk 1]
```diff
@@ -597,14 +597,14 @@ local function StartBidding()
     MonDKP:BroadcastBidTimer(core.BiddingWindow.bidTimer:GetText(), core.BiddingWindow.item:GetText().." Cost: "..core.BiddingWindow.cost:GetNumber()..perc, CurrItemIcon)
     MonDKP.Sync:SendData("MonDKPCommand", "BidInfo,"..core.BiddingWindow.item:GetText()..","..core.BiddingWindow.cost:GetText()..perc..",0,"..CurrItemIcon)
     MonDKP:BidInterface_Toggle()
-    MonDKP:CurrItem_Set(core.BiddingWindow.item:GetText(), core.BiddingWindow.cost:GetText()..perc, CurrItemIcon)
+    MonDKP:CurrItem_Set(core.BiddingWindow.item:GetText(), core.BiddingWindow.cost:GetText()..perc, core.BiddingWindow.maxBid:GetText()..perc, CurrItemIcon)
```
Comment (lantisnt) [inline Modules/Bidding.lua]:
```suggestion
    MonDKP:CurrItem_Set(core.BiddingWindow.item:GetText(), core.BiddingWindow.cost:GetText()..perc, 0, CurrItemIcon)

```

**Comment by lantisnt** [comment]
Covered also by https://github.com/Roeshambo/MonolithDKP/pull/341 - change max to be backward compatible
